<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tache;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveData($data)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('DELETE FROM AppBundle:Tache');
        $query->execute();

        /** @var ProjetRepository $projetRepo */
        $projetRepo = $em->getRepository('AppBundle:Projet');
        $projetIdByRefs = $projetRepo->AllIdByRefs();

        /** @var cfcRepository $cfcRepo */
        $cfcRepo = $em->getRepository('AppBundle:Cfc');
        $cfcIdByRefs = $cfcRepo->AllIdByRefs();

        foreach( $data as $elem) {
            $tache =  new Tache();
            $tache->setName(isset($elem['name']) ? $elem['name'] : null);
            $tache->setDescription(isset($elem['description']) ? $elem['description'] : null);
            $tache->setRef(isset($elem['ref']) ? $elem['ref'] : null);
            $tache->setName(isset($elem['name']) ? $elem['name'] : null);
            $tache->setProjet(isset($projetIdByRefs[$elem['projet']]) ? $projetIdByRefs[$elem['projet']]: null);
            $tache->setCfc(isset($cfcIdByRefs[$elem['cfc']]) ? $cfcIdByRefs[$elem['cfc']] : null);
            $em->persist($tache);
        }
        $em->flush();
    }


}
